# =========================Service setting=========================
services:
  #  web api service
  webapi:
    # build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5289:5289"
      - "7074:7074"
    # Let container's status is sleep that devcontainer
    command: sleep infinity

  # sqslserver service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      # psaaword must be strong instead of that container can't run
      - SA_PASSWORD=P@sswords715981432
    ports:
      - "1433:1433"
    # volumes:we can use volumes to persist data
    volumes:
      - sqlserver_data_BusInfoSys:/var/opt/mssql

  # ngrok service
  # ngrok is a tool that creates a secure tunnel to your localhost
  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    command: http webapi:5289
    environment:
      - NGROK_AUTHTOKEN=2x4JS0YDI8Cdu8vewI5nQzKnOV3_7ir9igEbpKuLqNBprdJmB
    ports:
      - "4040:4040"
volumes:
  sqlserver_data_BusInfoSys:



